name: LeetCode Sync

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: leetcode
          verbose: true
